### ISSUE TITLE
运行 react-native run-android 报错

### ISSUE THREAD

**Issue by hq001a** [crazycodeboy/GitHubPopular#3]
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at com.android.build.gradle.BasePlugin$$Lambda$23/410033330.execute(Unknown Source)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'security''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by crazycodeboy** [comment]
从log上看应该是环境配置的问题，可以参考@http://stackoverflow.com/questions/32153544/errorcause-buildtoolsversion-is-not-specified

**Comment by hq001a** [comment]
stackoverflow认为不同层级的gradle里写错了，我是直接clone你代码 npm install 然后运行，自己没有动过gradle的代码，所以这个不是问题所在的感觉。

**Comment by crazycodeboy** [comment]
通过`npm install`把依赖包安装一下   
``` 
    "react-native-check-box": "^1.0.0",
    "react-native-easy-toast": "^1.0.2",
    "react-native-htmlview": "^0.5.0",
    "react-native-parallax-scroll-view": "^0.19.0",
    "react-native-scrollable-tab-view": "^0.5.3",
    "react-native-sortable-listview": "^0.1.1",
    "react-native-splash-screen": "^1.0.9",
    "react-native-tab-navigator": "^0.3.3"
```

**Comment by marsrandy** [comment]
我也是报的这个错误 npm install 完成后，第一次运行 react-native run-android 就出错了，log里还可以看到正下完了guava-18.0.jar 包
Download https://jcenter.bintray.com/com/google/guava/guava/18.0/guava-18.0.jar
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
        .......

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating project ':app'.
> A problem occurred starting process 'command 'security''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10 mins 19.574 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

######### Finished executing: react-native.cmd run-android ##########
[Error : 0104]  Failed to run the application in Android: Unknown error

**Comment by crazycodeboy** [comment]
@marsrandy 相关依赖包需要完全下载成功后才能编译运行，另外，可以通过AndroidStudio编译运行这样方面查找问题

**Comment by marsrandy** [comment]
用 Android Studio 打开 GitHubPopular\android 提示错误
* Gradle 'android' project refresh failed
> Error: CreateProcess error=2, 系统找不到指定文件。
-_-!

**Comment by crazycodeboy** [comment]
相应的依赖库没有全部安装？

**Comment by marsrandy** [comment]
package.json 全都重装过了

**Comment by marsrandy** [comment]
Android Studio log显示

> Consult IDE log for more details (Help | Show Log) 
2016-10-25 17:06:45,770 [ 635059]   WARN - roid.tools.ndk.GradleWorkspace - NDK support for project 'android' is disabled because the project doesn't contain any valid native configurations. 
2016-10-25 17:06:45,839 [ 635128]   INFO -       #com.jetbrains.cidr.lang - Clearing symbols finished in 0 s. 
2016-10-25 17:06:45,839 [ 635128]   INFO -       #com.jetbrains.cidr.lang - Loading symbols finished in 0 s. 
2016-10-25 17:06:45,874 [ 635163]   INFO -       #com.jetbrains.cidr.lang - Building symbols finished in 0 s. 
2016-10-25 17:06:45,875 [ 635164]   INFO -       #com.jetbrains.cidr.lang - Saving symbols finished in 0 s. 
2016-10-25 17:08:23,069 [ 732358]   INFO - tion.impl.ExecutionManagerImpl - Module 'android' is not backed by gradle 
com.intellij.execution.CantRunException: Module 'android' is not backed by gradle

**Comment by crazycodeboy** [comment]
@marsrandy 这是应该是Android Studio 的配置问题你stackoverflow.com一下

**Comment by michaelguo1991** [comment]
我遇到了同样的问题， log中显示的详细错误为：A problem occurred starting process 'command 'security''
把build.gradle中getPassword方法注释掉后可以运行
![image](https://cloud.githubusercontent.com/assets/2106440/19681369/b73d5b42-9adb-11e6-815f-27d42a96c96e.png)

**Comment by crazycodeboy** [comment]
将`signingConfig signingConfigs.release`注掉即可，
```
 buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            //signingConfig signingConfigs.release
        }
    }
```
这是因为GitHubPopular签名打包时的设置，更多可参考[React Native发布APP之签名打包APK](http://www.devio.org/2016/07/23/react-native-%E5%8F%91%E5%B8%83APP%E4%B9%8B%E7%AD%BE%E5%90%8D%E6%89%93%E5%8C%85APK/)

**Comment by marsrandy** [comment]
终于可以运行了，按照 @michaelguo1991 的方法试了还是报错， 然后按 @crazycodeboy 的方法也还是报错， 但问题应该是打包发布APK的问题，所以我把 
gradle.properties 文件和  android/app/build.gradle 文件里，用于打包APK添加的内容全注释掉了，那样再运行 react-native run-android 的时候安全通过了

**Comment by wangyihang875** [comment]
@marsrandy 用于打包APK添加的内容具体是哪些?

**Comment by YeomanYe** [comment]
@michaelguo1991 
你的图片是怎么加进来的啊
