### ISSUE TITLE
watch EPERM

### ISSUE THREAD

**Issue by hq001a** [crazycodeboy/GitHubPopular#5]
ERROR  watch F:\360Downloads\GitHubPopular-master\GitHubPopular-master\android\app\build\intermediates\exploded-aar\GitHubPopular\react-native-splash-screen\unspecified\jars EPERM
{"code":"EPERM","errno":"EPERM","syscall":"watch F:\\360Downloads\\GitHubPopular-master\\GitHubPopular-master\\android\\app\\build\\intermediates\\exploded-aar\\GitHubPopular\\react-native-splash-screen\\unspecified\\jars","filename":"F:\\360Downloads\\GitHubPopular-master\\GitHubPopular-master\\android\\app\\build\\intermediates\\exploded-aar\\GitHubPopular\\react-native-splash-screen\\unspecified\\jars"}
Error: watch F:\360Downloads\GitHubPopular-master\GitHubPopular-master\android\app\build\intermediates\exploded-aar\GitHubPopular\react-native-splash-screen\unspecified\jars EPERM
    at exports._errnoException (util.js:953:11)
    at FSWatcher.start (fs.js:1423:19)
    at Object.fs.watch (fs.js:1450:11)
    at NodeWatcher.watchdir (F:\360Downloads\GitHubPopular-master\GitHubPopular-master\node_modules\sane\src\node_watcher.js:144:20)
    at Walker.<anonymous> (F:\360Downloads\GitHubPopular-master\GitHubPopular-master\node_modules\sane\src\node_watcher.js:353:12)
    at emitTwo (events.js:106:13)
    at Walker.emit (events.js:191:7)
    at F:\360Downloads\GitHubPopular-master\GitHubPopular-master\node_modules\walker\lib\walker.js:69:16
    at go$readdir$cb (F:\360Downloads\GitHubPopular-master\GitHubPopular-master\node_modules\graceful-fs\graceful-fs.js:149:14)
    at go$readdir$cb (F:\360Downloads\GitHubPopular-master\GitHubPopular-master\node_modules\graceful-fs\graceful-fs.js:149:14)

**Comment by hq001a** [comment]
这错误是什么意思/(ㄒoㄒ)/~~

**Comment by hq001a** [comment]
重新npm install ok了
