### ISSUE TITLE
java.io.IOException: Cannot run program "security" (in directory  "D:\GitHubPopular\android\app")

### ISSUE THREAD

**Issue by haoqichongtian** [crazycodeboy/GitHubPopular#81]
This process isn't exist in the git repository,why it need to be excute?
`Caused by: java.io.IOException: Cannot run program "security" (in directory "D:\GitHubPopular\android\app"): CreateProcess error=2, 系统找不到指定的文件。
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, `

**Comment by StevenZhangHl** [comment]
一样的问题，我的gradle报错就是这个
 exec {
        commandLine 'security', '-q', 'find-generic-password', '-a', currentUser, '-s', keyChain, '-w'
        standardOutput = stdout
        errorOutput = stderr
        ignoreExitValue true
    }
就是这段代码里的security找不到

**Comment by MelodyGoing** [comment]
我也遇到同样的问题
